### PR TITLE
FM2-243: Fix test errors on Windows

### PR DESCRIPTION
**Pull request by ShivanshRakesh**
## Description of what I changed

Trimming the trailing whitespaces instead of comparison with `\n` in assertion tests.

## Issue I worked on

see https://issues.openmrs.org/browse/FM2-243

## Checklist: I completed these to help reviewers :)

- [x] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

- [x] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

- [x] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

- [x] All new and existing **tests passed**.

- [x] My pull request is **based on the latest changes** of the master branch.

### CODE REVIEW

**Comment by ShivanshRakesh** [comment]
@gitcliff Could you check if the build succeeds on Windows?

**Comment by sherrif10** [comment]
Thanks @ShivanshRakesh  its has worked perfect on windows, i think its ready to be merged, @gitcliff  how about you ?

**Comment by ShivanshRakesh** [comment]
😃 Thanks for checking it out @sherrif10!

**Comment by ShivanshRakesh** [comment]
Thanks @ibacher!

**Pull request merged**
