### PR TITLE
FHIR2 to not be aware of legacyui module

### PR DESCRIPTION
**Pull request by Ruhanga**
## Issue I worked on

Related to https://issues.openmrs.org/browse/TRUNK-6054

## Checklist: I completed these to help reviewers :)

- [x] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

- [x] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

- [x] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

- [x] All new and existing **tests passed**.

- [x] My pull request is **based on the latest changes** of the master branch.

### CODE REVIEW

**Review by Ruhanga — COMMENTED** [review]
Hi @ibacher, does the fhir2 module need to be aware of the legacyui module? I'm removed the awareness which otherwise causes unexpected behaviour specifically in the context of using it with modules like the oauth2login which in turn is aware of the fhir2 module. This is related to [this ticket](https://issues.openmrs.org/browse/TRUNK-6054).

**Comment by ibacher** [comment]
@Ruhanga I don't think we technically need to be aware of it right now, but I'm not sure I can guarantee that will always be the case (we currently don't have any form of UI, but that might change).

**Comment by ibacher** [comment]
Is this intended to be a draft?

**Comment by Ruhanga** [comment]
Thanks for the review @ibacher. I've made the PR ready for review/merging.

**Pull request merged**
