### PR TITLE
FM2-121: Remove condition resource implementation for openmrs platform v2.0 -2.1

### PR DESCRIPTION
**Pull request by corneliouzbett**
## Description of what I changed

Remove condition implementation for openmrs platform version 2.0 -2.1

## Issue I worked on

see https://issues.openmrs.org/browse/FM2-121

## Checklist: I completed these to help reviewers :)

- [x] My pull request only contains **ONE single commit**.

  No? -> [read here](https://wiki.openmrs.org/display/docs/Pull+Request+Tips) on how to squash multiple commits into one

- [x] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [x] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [x] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [x] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [x] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

### CODE REVIEW

**Comment by jecihjoy** [comment]
There is no any condition related functionality  in 2.1, @corneliouzbett did you intend to say 2.0 and 2.2?

**Comment by corneliouzbett** [comment]
> There is no any condition related functionality in 2.1, @corneliouzbett did you intend to say 2.0 and 2.2?

The current implementation in api-2.0 submodule supports from openmrs platform version **2.0.5 to 2.1.*** and that's what I am removing.

**Comment by joachim-junior** [comment]
@corneliouzbett,  I don't really understand your scope, but firstly looking at the prerequisites from description, your pull request and files looks very fine . Can't really figure out the problem here. Well did you do a test before the PR ?

**Comment by ibacher** [comment]
Thanks Bett!

**Pull request merged**
