### PR TITLE
FM2-180: Update allergyIntoleranceComponent.getReaction to use all reactions

### PR DESCRIPTION
**Pull request by corneliouzbett**
## Description of what I changed

Update manifestation to loop for all reactions
## Issue I worked on

see https://issues.openmrs.org/browse/FM2-180

## Checklist: I completed these to help reviewers :)

- [ ] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [ ] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [ ] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [ ] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [ ] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

### CODE REVIEW

**Comment by corneliouzbett** [comment]
> So the reason I was getting the value at index 0 is that the way the allergies work is each allergy will contain only one AllergyIntoleranceReactionComponent which is a component containing reactions (manifestations in fhir), allergy substance and the severity value. So that means that all the allergy reactions will be mapped

This is the code for translating allergy reactions to fhir;
```java
List<CodeableConcept> manifestations = new ArrayList<>();
for (AllergyReaction reaction : reactions) {	
manifestations.add(conceptTranslator.toFhirResource(reaction.getReaction()).setText(reaction.getReactionNonCoded()));
}
return manifestations;
```
This means your be having more than one manifestations if there are more than one allergy reactions.

**Comment by jecihjoy** [comment]
The openmrs allegry reactions are mapped to AllergyIntoleranceReactionComponent.manifestation and not to AllergyIntoleranceReactionComponent directly. That means regardless the number of reactions they'll all be represented as list of manifestations/CodeableConcept inside AllergyIntoleranceReactionComponent

**Comment by jecihjoy** [comment]
currently this is what we have is https://pastebin.com/2UbFMEut

What your mapping. suggests is for each reaction, we should create an AllergyIntoleranceReactionComponent ie something like https://pastebin.com/baYApTT6

The two sample json(s) are when we're having two allergy reactions

**Comment by corneliouzbett** [comment]
> currently this is what we have is https://pastebin.com/2UbFMEut
> 
> What your mapping. suggests is for each reaction, we should create an AllergyIntoleranceReactionComponent ie something like https://pastebin.com/baYApTT6
> 
> The two sample json(s) are when we're having two allergy reactions

That's correct. The problem is when you are translating back to openmrsType. It will only translate at index 0. So what about the rest??

**Comment by jecihjoy** [comment]
> > currently this is what we have is https://pastebin.com/2UbFMEut
> > What your mapping. suggests is for each reaction, we should create an AllergyIntoleranceReactionComponent ie something like https://pastebin.com/baYApTT6
> > The two sample json(s) are when we're having two allergy reactions
> 
> That's correct. The problem is when you are translating back to openmrsType. It will only translate at index 0. So what about the rest??

When translating back to openmrs allergy reactions i'm looping backs the list of manifestations codeable concepts, and it's working just fine because that's  what I used to create new allergies and I was saving allergies with multiple reactions

**Comment by corneliouzbett** [comment]
> currently this is what we have is https://pastebin.com/2UbFMEut
> 
> What your mapping. suggests is for each reaction, we should create an AllergyIntoleranceReactionComponent ie something like https://pastebin.com/baYApTT6
> 
> The two sample json(s) are when we're having two allergy reactions

Translating to fhirType is Ok. Using the two JSON samples try translating back to openmrs allergy reactions. If I am right will get oner

**Comment by corneliouzbett** [comment]
> > > currently this is what we have is https://pastebin.com/2UbFMEut
> > > What your mapping. suggests is for each reaction, we should create an AllergyIntoleranceReactionComponent ie something like https://pastebin.com/baYApTT6
> > > The two sample json(s) are when we're having two allergy reactions
> > 
> > 
> > That's correct. The problem is when you are translating back to openmrsType. It will only translate at index 0. So what about the rest??
> 
> When translating back to openmrs allergy reactions i'm looping backs the list of manifestations codeable concepts, and it's working just fine because that's what I used to create new allergies and I was saving allergies with multiple reactions

```java
for (CodeableConcept code : fhirAllergy.getReaction().get(0).getManifestation()) {
				reactions.add(new AllergyReaction(allergy, conceptTranslator.toOpenmrsType(code), code.getText()));
}
```
This code here disagree with what you are saying.
what about `fhirAllergy.getReaction().get(1...n)` ?

**Comment by jecihjoy** [comment]
> ```java
> t(0).getManifestation()
> ```

The emphasis is on getManifestation @corneliouzbett 

for (CodeableConcept code : fhirAllergy.getReaction().get(0)**.getManifestation()**)

Manifestation property is what's holding the reactions

**Comment by corneliouzbett** [comment]
> > ```java
> > t(0).getManifestation()
> > ```
> 
> The emphasis is on getManifestation @corneliouzbett
> 
> for (CodeableConcept code : fhirAllergy.getReaction().get(0)**.getManifestation()**)
> 
> Manifestation property is what's holding the reactions

FYI this PR doesn't change the current functionality. It's an enhancement. Are certain(💯 sure) that `fhirAllergy.getReaction()` will always have one AllergyIntoleranceReactionComponent? 

What happens when `fhirAllergy.getReaction()` is empty meaning value at index 0 doesn't exists. So `fhirAllergy.getReaction().get(0)` will definitely throw an error. I hope you see my point now

Just go through what I have changed once more. It should make sense.

**Comment by jecihjoy** [comment]
As of this `What happens when fhirAllergy.getReaction() is empty meaning value at index 0 doesn't exists. So fhirAllergy.getReaction().get(0) will definitely throw an error. I hope you see my point now`
there is this check https://github.com/openmrs/openmrs-module-fhir2/blob/a5dbd6f140d70159cce694d3b42888de2362b040/api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/AllergyIntoleranceTranslatorImpl.java#L155

**Pull request merged**
