### PR TITLE
FM2-143 : Implement generic Dao classes to ensure code reuse in the Dao layer

### PR DESCRIPTION
**Pull request by jecihjoy**
## Description of what I changed
Implemented generic Dao classes to ensure code reuse in the Dao layer

## Issue I worked on

see https://issues.openmrs.org/browse/FM2-143

## Checklist: I completed these to help reviewers :)

- [x] My pull request only contains **ONE single commit**.

  No? -> [read here](https://wiki.openmrs.org/display/docs/Pull+Request+Tips) on how to squash multiple commits into one

- [x] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [x] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [x] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [x] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [x] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

### CODE REVIEW

**Comment by jecihjoy** [comment]
The commented tests are throwing NPE. This is specifically because the implementations are in the base class and i'm only calling super()
@corneliouzbett @ibacher how can I test this ? Does that mean I have to instantiate the base class in this test class?

**Comment by ibacher** [comment]
@jecihjoy: Remove the `SessionFactory` field from the `FhirMedicationDaoImpl` class. Also, looking at this again, I'd make the `SessionFactory` class in the base class `private` and add annotations to get the getter and setter:

```java
@Autowired
@Qualifier("sessionFactory")
@Getter(AccessLevel.PROTECTED)
@Setter(AccessLevel.PROTECTED)
private SessionFactory sessionFactory;
```

Essentially, the `SessionFactory` field in `FhirMedicationDaoImpl` is masking the `SessionFactory` field in `BaseFhirDaoImpl`.

**Comment by tendomart** [comment]
@ibacher  do you want her to use **DBSessionFactory** instead

**Comment by ibacher** [comment]
@tendomart Based on the comments for that class, no:

> [DBSessionFactory] should be used instead of SessionFactory for modules, which need to support OpenMRS 1.12 and before. Please do not use it, if you only need to support OpenMRS 1.12 and later.

She's doing the right thing, we just need to be sure we're setting the right object in the test!

**Comment by jecihjoy** [comment]
@ibacher getting rid of the child class session object and adding setters, getters for the base class session object fixed this

**Comment by tendomart** [comment]
Thanks for the clarity ?

**Pull request merged**
