### PR TITLE
FM2-613: Upgrade Hapi Fhir version to v5.7.9

### PR DESCRIPTION
**Pull request by mherman22**
## Description of what I changed

https://github.com/hapifhir/org.hl7.fhir.core/tree/master/org.hl7.fhir.convertors

## Issue I worked on

see https://issues.openmrs.org/browse/FM2-613

## Checklist: I completed these to help reviewers :)

- [x] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [x] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [x] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [x] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [x] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

### CODE REVIEW

**Review by mherman22 — COMMENTED** [review]
There is need to create a custom class that inherits the VersionConvertorFactory_30_40 class since in this version of Hapi Fhir, accessing convertion class is no longer possible.

[Quoted from here!](https://github.com/hapifhir/org.hl7.fhir.core/tree/master/org.hl7.fhir.convertors)-> Note that these classes are not intended to be used directly. When actually converting resources, the provided conversion factory classes are intended to be used as the entry point. For example, to convert a dstu3 AllergyIntolerance resource, the above conversion would not use AllergyIntolerance40_50 directly, but would instead call: VersionConvertorFactory_40_50.convertResource(dstu3AllergyIntolerance). VersionConvertorFactory_40_50 would call AllergyIntolerance40_50 internally to convert r4AllergyIntolerance.

cc: @ibacher

**Comment by mherman22** [comment]
> There is need to create a custom class that inherits the VersionConvertorFactory_30_40 class since in this version of Hapi Fhir, accessing convertion class is no longer possible.
> 
> [Quoted from here!](https://github.com/hapifhir/org.hl7.fhir.core/tree/master/org.hl7.fhir.convertors)-> Note that these classes are not intended to be used directly. When actually converting resources, the provided conversion factory classes are intended to be used as the entry point. For example, to convert a dstu3 AllergyIntolerance resource, the above conversion would not use AllergyIntolerance40_50 directly, but would instead call: VersionConvertorFactory_40_50.convertResource(dstu3AllergyIntolerance). VersionConvertorFactory_40_50 would call AllergyIntolerance40_50 internally to convert r4AllergyIntolerance.
> 
> cc: @ibacher

which explains the failing test on Tasks

**Comment by ibacher** [comment]
@mherman22 Sorry, I missed this PR until now. Yep, that looks to be a problem. I'm going to try a couple of things to see if we can avoid doing that, since it sounds like a lot of code.

**Comment by ibacher** [comment]
Well, we've got a new error now, I guess. Not sure if HAPI moved where the Pointcut definitions are stored?

**Comment by mherman22** [comment]
These very tests were failing in intellij and when i ran `mvn clean package` in the terminal, they were still failing. However, when i ran `mvn clean install` in the terminal, it was all successful and it seemed to install so many artifacts from the new version(`v5.7.9`). so when i triggered `mvn clean package` again, everything passes and in the IDE aswell.

So, the PointCut class didnt really change that much in the version(`5.7.9`) -> https://github.com/hapifhir/hapi-fhir/blob/v5.7.9/hapi-fhir-base/src/main/java/ca/uhn/fhir/interceptor/api/Pointcut.java

FYI: i was following the conversation at https://github.com/hapifhir/hapi-fhir/issues/316#issuecomment-201535063, especially that comment.

cc: @ibacher

**Comment by ibacher** [comment]
@mherman22 Are you running `mvn clean install -P integration-test` or similar?

**Comment by mherman22** [comment]
> @mherman22 Are you running `mvn clean install -P integration-test` or similar?

I guess I should run that and report back.

**Comment by ibacher** [comment]
So, it looks like this problem arises because of the version of Jackson we're using. I don't see any easy way forward that will continue to support older versions of OpenMRS.

In any case, we were going to dump support for pre-2.4.x versions at some point, so I guess that's now a prerequisite for this.

**Comment by ibacher** [comment]
@mherman22 Would you be able to take care of getting this PR to work with the new 2.0.0-SNAPSHOT version?

**Comment by mherman22** [comment]
> @mherman22 Would you be able to take care of getting this PR to work with the new 2.0.0-SNAPSHOT version?

Alright, lemi do that

**Comment by mherman22** [comment]
@ibacher you can take a look.

**Review by ibacher — APPROVED** [review]

**Comment by ibacher** [comment]
Nice work @mherman22!

**Pull request merged**
