### PR TITLE
FM2-19: SAXParseException on Platform 2.1.4

### PR DESCRIPTION
**Pull request by ibacher**
## Description of what I changed

Updates to use newer PropertySourcesPlaceholderConfigurer bean rather
than old-style property-placeholder.

## Issue I worked on

see https://issues.openmrs.org/browse/FM2-

## Checklist: I completed these to help reviewers :)

- [x] My pull request only contains **ONE single commit**.

  No? -> [read here](https://wiki.openmrs.org/display/docs/Pull+Request+Tips) on how to squash multiple commits into one

- [x] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [ ] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

  Skipped this as currently this behavior is not used anywhere. 

- [ ] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command
  
  Skipped this step as XML is not reformatted; this keeps the PR clean.

- [x] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [x] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

### CODE REVIEW

**Comment by corneliouzbett** [comment]
LGTM

**Comment by jecihjoy** [comment]
The changes only allows  mvn clean install -DskipTests -Dlicense.skip=true but running mvn clean install breaks most of the tests. Tested this with openmrs 2.1.4

**Comment by ibacher** [comment]
@jecihjoy `mvn clean install` works both on my machine and on the Travis CI environment, which is entirely clean. Could you post the test failures you're seeing?

**Comment by corneliouzbett** [comment]
Thanks @ibacher for the fix

**Pull request merged**
