### PR TITLE
FM2-469: Remove the FhirDurationUnitMap

### PR DESCRIPTION
**Pull request by mseaton**
See: https://issues.openmrs.org/projects/FM2/issues/FM2-469

### CODE REVIEW

**Review by ibacher — APPROVED** [review]

**Comment by ibacher** [comment]
Thanks @mseaton! This is great!

**Comment by mseaton** [comment]
Looks like I needed to run integration tests explicitly.  Doing that now and will fix.  @ibacher

**Comment by ibacher** [comment]
Ah, yes, I should probably add a note to the README. I find it helpful to be able to just fix the unit tests and not worry about the integration tests, so they're default disabled. Alternatively, maybe I should invert that and I can just run with `-p !integration-test`?

**Comment by mseaton** [comment]
Updated the integration test data, building now...

**Pull request merged**
