### PR TITLE
FM2-299: Add necessary Javadoc to methods and classes

### PR DESCRIPTION
**Pull request by ShivanshRakesh**
## Description of what I changed

Added Javadocs to methods and classes created under [FM2-192](https://issues.openmrs.org/browse/FM2-299).

## Issue I worked on

see https://issues.openmrs.org/browse/FM2-299

## Checklist: I completed these to help reviewers :)

- [x] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

- [x] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

- [x] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

- [x] All new and existing **tests passed**.

- [x] My pull request is **based on the latest changes** of the master branch.

### CODE REVIEW

**Comment by ShivanshRakesh** [comment]
@ibacher @HerbertYiga @suthagar23 PTAL.

**Review by HerbertYiga — APPROVED** [review]
Thanks @ShivanshRakesh  cc @ibacher

**Comment by ShivanshRakesh** [comment]
Thanks @HerbertYiga!

**Comment by HerbertYiga** [comment]
hi @ibacher is this good for merging?

**Comment by ShivanshRakesh** [comment]
I've resolved the conflicts. PTAL!
cc @ibacher @HerbertYiga @suthagar23

**Comment by ShivanshRakesh** [comment]
@ibacher Could we merge this?

**Review by Akayeshmantha — APPROVED** [review]
LGTM

**Review by ibacher — APPROVED** [review]

**Comment by ShivanshRakesh** [comment]
Thanks @ibacher!

**Pull request merged**
