### PR TITLE
FM2-572: Improve performance for total count in results

### PR DESCRIPTION
**Pull request by rkorytkowski**
## Issue I worked on

see https://issues.openmrs.org/browse/FM2-

## Checklist: I completed these to help reviewers :)

- [x] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [ ] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [x] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [x] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [x] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

### CODE REVIEW

**Comment by rkorytkowski** [comment]
I'll update openmrs-core to enable query cache by default for this feature to work. 

I can't update JIRA for now as there seems to be login issue... I'll update as soon as it starts working again for me.

**Review by ibacher — APPROVED** [review]

**Comment by ibacher** [comment]
We still need to surface this to the actual API via the `providers`, but this looks like a good implementation of this. I assume things don't break when using older verisons of core, the caching is just not enabled? (We support back to core 2.0.5 at present).

**Comment by rkorytkowski** [comment]
> We still need to surface this to the actual API via the `providers`

Could you please explain?

**Comment by rkorytkowski** [comment]
> I assume things don't break when using older verisons of core, the caching is just not enabled? (We support back to core 2.0.5 at present).

It's completely ignored if caching is not enabled globally via hibernate properties.

**Comment by ibacher** [comment]
Yeah, so the actual API for this is provided by the HAPI library using their `IResourceProvider` interface. But to make the parameter actually something user's can toggle with the API, the argument needs to be part of the method marked with the `@Search` parameter in those classes, like [this one](https://github.com/openmrs/openmrs-module-fhir2/blob/356a3b36c2b4b10a9366e7b23fba33659f2b161b/api/src/main/java/org/openmrs/module/fhir2/providers/r4/ObservationFhirResourceProvider.java#L93). These providers are all in the `org.openmrs.module.fhir2.providers` package in the various `api` subprojects, i.e., the bulk of them are [here](https://github.com/openmrs/openmrs-module-fhir2/tree/master/api/src/main/java/org/openmrs/module/fhir2/providers).

Doesn't need to be part of this PR, just future work we'll need to do to add, e.g.,

`@OptionalParameter(name = EXACT_TOTAL_SEARCH_PARAMETER) exactTotalSearch`

To the search methods.

**Pull request merged**
