### PR TITLE
Support for SmartConfigServlet for Smart Conformance

### PR DESCRIPTION
**Pull request by VaishSiddharth**
## Issue I worked on

see https://issues.openmrs.org/browse/FM2-239

## Checklist: I completed these to help reviewers :)

- [x] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [x] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [x] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [x] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [x] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

### CODE REVIEW

**Comment by HerbertYiga** [comment]
@VaishSiddharth  thanks for the work on this,you can improve the ticket description  too

**Comment by ibacher** [comment]
@VaishSiddharth Do we need this with the current smartonfhir module?

**Comment by VaishSiddharth** [comment]
@ibacher  No we don't as we have made `SmartForwardingFilter` in the smartonfhir module

**Comment by ibacher** [comment]
@VaishSiddharth Thanks! That's what I thought, but I wanted to be sure before closing this.

**Pull request closed without merging**
